name: Prerelease Tag
on:
  release:
    types: [prereleased]

jobs:
  run:
    name: Set Prerelease Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag or branch with this input.
          # Default: 'latest'
          ref: prerelease-latest

          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Default: ''
          #description: Description for the tag

          # Force-update a branch instead of using a tag.
          # Default: false
          #force-branch: true
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
